config/routes.rb
Formplay::Application.routes.draw do
  resources :document_signatories

  resources :documents

  resources :people

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :name, :document_signatories_attributes
  
  belongs_to :person
  
  has_many :document_signatories, :dependent => :destroy
  has_many :signatories, :through=>:document_signatories, :source=>:signatory, :dependent => :destroy
  
  
  accepts_nested_attributes_for :signatories, :allow_destroy => true
  accepts_nested_attributes_for :document_signatories, 
                                :allow_destroy => true
                                
  validates_presence_of :name
  
  validates_associated :document_signatories
  
  validate :must_have_document_signatory_type_and_signatory
  
  # http://stackoverflow.com/questions/5144527/nested-models-and-parent-validation
  def must_have_document_signatory_type_and_signatory
    if self.document_signatories.reject(&:marked_for_destruction?).empty?
      errors.add(:base, 'Must have a valid document signatory')
    end
  end
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  
  # Remove div created for the adding of new rows before we pass it on to the models
  before_filter :remove_hidden_signatory
  
  
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new

    # Here we build the association for the form with a new blank document_signatory so that the 
    # form builder can build the fields for us
    @document = Document.new
    ds = @document.document_signatories.build
    ds.build_signatory

    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
  
  private

    def remove_hidden_signatory
      params[:document][:document_signatories_attributes].delete("new_document_signatories") unless 
        params[:document].nil? or  params[:document][:document_signatories_attributes].nil?     
    end
  
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= nested_form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "document name"%><br />
    <%= f.text_field :name %>

    <%
    pp "f.object.document_signatories"
    pp f.object.document_signatories


    %>
  
  <div class="field">
    <%= f.fields_for :document_signatories, 
          f.object.document_signatories.empty? ? 
          f.object.document_signatories.build : 
          :document_signatories  do |f2| %>
      <%= f2.label :signatory_type, "signatory type"%><br />
      <%= f2.text_field :signatory_type %>
      <%= f2.link_to_remove "Remove this Document Signatory"%>

<%
pp "f2.object.signatory.nil?"
pp f2.object.signatory.nil?



%>

      <div class="field">
        <%= f2.fields_for :signatory, f2.object.signatory.nil? ? f2.object.build_signatory : :signatory do |f3| %>
          <%= f3.label :name, "person name"%><br />
          <%= f3.text_field :name %>
          <%= f2.link_to_remove "Remove this Signatory"%>
        <%end%>
        <%#= f2.link_to_add "Add a Signatory", :signatory -%>
      </div>
      
   
 
  
    <%end%>
    
    <%#= f.link_to_add "Add a Document Signatory", :document_signatories, :create_blank_submodel => :signatory %>
    <%= f.link_to_add "Add a Document Signatory", :document_signatories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th>Document Name</th>
    <th>Document Owner Person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.name %></td>
    <td><%= document.person.name unless document.person.nil? %></td>
    <td><%= link_to 'Show', document %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Document Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Document Signatories:</b>
  <%= @document.document_signatories %>
</p>

<p>
  <b>Signatories:</b>
  <%= @document.signatories %>
</p>

<p>
  <b>Document Signatories People:</b>
  <%= @document.document_signatories.each do |ds|  %>
    <%= ds.signatory %>
  <%end%>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>